### PR TITLE
Support connectors validation client-side & Minor fixes

### LINKED ISSUE #86: While signing a forfeit transaction, the client should be able to verify connector input
Forfeit transactions include a connector input related to the current round. Before signing them, the client should check the validity of that connector (is it linked to the next round transaction)

### PR DESCRIPTION
**Pull request by altafan**
This makes the client validate the connectors sent by the asp during the round finalization by checking that each tx of the chain contains the expected prevout as input.

For this, the list of connectors has been added to the proto event in order to be received by the client.

Closes #86 

Please @louisinger review this.

### CODE REVIEW

File: client/common.go [hunk 1]
```diff
@@ -430,12 +432,16 @@ func handleRoundStream(
...
 			// validate the congestion tree
 			if err := tree.ValidateCongestionTree(
-				congestionTree, poolTxStr, aspPubkey, int64(roundLifetime),
+				congestionTree, poolTx, aspPubkey, int64(roundLifetime),
 			); err != nil {
 				return "", err
 			}
 
-			exitDelay, err := getUnilateralExitDelay()
+			if err := common.ValidateConnectors(poolTx, connectors); err != nil {
```
Comment (louisinger) [inline client/common.go:440]: I think we should also check that the connectors in forfeit transactions are the one we are validated (an ASP could send a valid connectors list but use others outpoints while building the forfeits.

Comment (louisinger) [reply client/common.go:440]: done by 2421382
