### PR TITLE
fix: "tree signing session not found" error

### LINKED ISSUE #308: client-sdk: error when claiming for the second time
When using Ark SDK in a always on server, claiming a transaction only works for the first time.

I think the treeSignerSession object (used in Claim)  keeps in cache the nonces used on the first claim, which conflicts with the second claim (different VTXOs, should be diff nonces).

When I restart the always on server, the object is cleared, so it works again for one claim.

### PR DESCRIPTION
**Pull request by louisinger**
_This PR contains hotfixes regarding the tree signing session during claim. It adds a test to reproduce the error. It also includes a fix in btc-embedded coinselection (unrelated to the original error but raised by the test)_

**Claim failing error**

The problem is coming from `handleRoundStream` SDK function receiving "RoundFinalized" event not related to the current round, making the SDK to register two times the same payment, causing the timeout error server side.

fix = ignore unrelated round finalized event client side + check for duplicate inputs while registering payments.

**Coin selection fixes**

- re-estimate fees when the wallet does several coin selection rounds, avoid min-relay-fee not met errors
- lease outputs while selecting utxos

it closes #308 

@altafan @bordalix please review

### CODE REVIEW

File: server/internal/infrastructure/tx-builder/covenantless/builder.go [hunk 1]
```diff
@@ -928,15 +934,47 @@ func (b *txBuilder) createPoolTx(
...
+
+			if dust == 0 {
+				if feeAmount == change {
+					// fees = change, remove change output
+					ptx.UnsignedTx.TxOut = ptx.UnsignedTx.TxOut[:len(ptx.UnsignedTx.TxOut)-1]
+					ptx.Outputs = ptx.Outputs[:len(ptx.Outputs)-1]
+				} else if feeAmount < change {
+					// change covers the fees, reduce change amount
+					ptx.UnsignedTx.TxOut[len(ptx.Outputs)-1].Value = int64(change - feeAmount)
+				} else {
```
Comment (altafan) [inline server/internal/infrastructure/tx-builder/covenantless/builder.go:951]: not sure this is enough: if change - fee amount is dust, we should drop the change amount and put everything on fees, shouldn't we?

Comment (altafan) [reply server/internal/infrastructure/tx-builder/covenantless/builder.go:951]: if yes, the same change must be done below too. Maybe better to move all the common code to a dedicated function?

**Comment by bordalix** [comment]
Tested it, and is not good.

Context: Alice had a couple of previous tx, but Bob is a fresh wallet.

1. Alice sends 12.345 sats to Bob
2. Bob claims tx (balance = 12.345) :white_check_mark:
3. Alice send 54.321 sats to Bob
4. Two (!) 54.321 tx appear on Bob :x:
5. Balance of Bob is 120.987 :x:

Screenshot 2024-09-18 at 15 49 11

The good news is Bob was able to claim the second time.

So, either Alice sent 2 VTXOs to Bob, or ListVtxos() is buggish and is returning one extra VTXO.

From Bob's VTXO list (after claiming) it seems to me the 2 last spent VTXOs are the same:

```
INFO[0389] spendableVtxos                               
INFO[0389] ---------                                    
INFO[0389] Amount 12345                                 
INFO[0389] ExpiresAt 2024-09-25 15:46:11 +0100 WEST     
INFO[0389] Pending false                                
INFO[0389] RoundTxid b67d82d9ce1de8518e1f7bbf34a3b8fa806b872441b07edf6b1ce71a5b5f6d73 
INFO[0389] Txid 314c06f505f2f8b2c24689531696cd0b5aaab1432635aa6e1c53bfeadaa4e9ae 
INFO[0389] SpentBy                                      
INFO[0389] ---------                                    
INFO[0389] ---------                                    
INFO[0389] Amount 108642                                
INFO[0389] ExpiresAt 2024-09-25 15:50:48 +0100 WEST     
INFO[0389] Pending false                                
INFO[0389] RoundTxid 7a51cb31737ad533e047f1ec245e13250c49cc13942f729d8b6d3963d84d2731 
INFO[0389] Txid 62df9d3030287652c4e2c0e09c835b7a22ea44e4aec7f8146525b1168b3223a6 
INFO[0389] SpentBy                                      
INFO[0389] ---------                                    
INFO[0389] spentVtxos                                   
INFO[0389] ---------                                    
INFO[0389] Amount 12345                                 
INFO[0389] ExpiresAt 2024-09-24 10:41:13 +0100 WEST     
INFO[0389] Pending true                                 
INFO[0389] RoundTxid                                    
INFO[0389] Txid a274304131857fb8901cf1c812646d5120a66c9cac08759806732e7eb5cb29d0 
INFO[0389] SpentBy b67d82d9ce1de8518e1f7bbf34a3b8fa806b872441b07edf6b1ce71a5b5f6d73 
INFO[0389] ---------                                    
INFO[0389] ---------                                    
INFO[0389] Amount 54321                                 
INFO[0389] ExpiresAt 2024-09-24 15:26:52 +0100 WEST     
INFO[0389] Pending true                                 
INFO[0389] RoundTxid                                    
INFO[0389] Txid a46e63c74ce3be6d5240a29e50121c4969c331158cecc58b9eebc6d4ac86d0ca 
INFO[0389] SpentBy 7a51cb31737ad533e047f1ec245e13250c49cc13942f729d8b6d3963d84d2731 
INFO[0389] ---------                                    
INFO[0389] ---------                                    
INFO[0389] Amount 54321                                 
INFO[0389] ExpiresAt 2024-09-24 15:26:52 +0100 WEST     
INFO[0389] Pending true                                 
INFO[0389] RoundTxid                                    
INFO[0389] Txid a46e63c74ce3be6d5240a29e50121c4969c331158cecc58b9eebc6d4ac86d0ca 
INFO[0389] SpentBy 7a51cb31737ad533e047f1ec245e13250c49cc13942f729d8b6d3963d84d2731 
INFO[0389] ---------  
```
