### PR TITLE
pubsub BatchFailed

### LINKED ISSUE #764: Add list of intent id hashes as metadata when batch fails
Let's add the `map[string]struct{}` of intent id hashes as metadata (`intents` key) when a batch fails. This way, it would make it easy for the clients listening to the stream to understand if the failed batch is related to them or not.

### PR DESCRIPTION
**Pull request by louisinger**
This PR modifies the `BatchFailed` event behavior. Now clients receive BatchFailed event based on subscribed topics. It reuses the input outpoints topics used to fetch connectors.

it requires to cache the poppedIntents array : LiveStore interface implements a new `GetPoppedIntents`.

@altafan @Kukks please review

it closes #764 

## Summary by CodeRabbit

* **New Features**
  * Added a Round Failed event to the event stream that includes topics describing affected inputs.

* **Improvements**
  * Round Finalized events now include the correct commitment transaction ID.
  * Recently selected/popped intents are now retrievable for improved traceability.
  * Insufficient-liquidity failures now return a generic "service temporary unavailable" response.

* **Tests**
  * Added tests validating retrieval and correctness of recently selected/popped intents.

### CODE REVIEW

File: internal/core/ports/live_store.go [hunk 1]
```diff
@@ -23,6 +23,7 @@ type IntentStore interface {
 	Len() int64
 	Push(intent domain.Intent, boardingInputs []BoardingInput, cosignersPublicKeys []string) error
 	Pop(num int64) []TimedIntent
+	GetPoppedIntents() []TimedIntent
```
Comment (altafan) [inline internal/core/ports/live_store.go]:
```suggestion
	GetSelectedIntents() []TimedIntent
```

File: internal/core/application/service.go [hunk 2]
```diff
@@ -2775,7 +2775,21 @@ func (s *service) propagateEvents(round *domain.Round) {
 		}
 		s.roundReportSvc.OpEnded(SendSignedTreeEventOp)
 	case domain.RoundFinalized:
-		lastEvent = RoundFinalized{lastEvent.(domain.RoundFinalized), round.CommitmentTxid}
+		lastEvent = RoundFinalized{ev, round.CommitmentTxid}
+	case domain.RoundFailed:
+		poppedIntents := s.cache.Intents().GetPoppedIntents()
```
Comment (altafan) [inline internal/core/application/service.go]:
```suggestion
		selectedIntents := s.cache.Intents().GetPoppedIntents()
```

File: internal/infrastructure/live-store/inmemory/intents.go [hunk 3]
```diff
@@ -15,16 +15,19 @@ type intentStore struct {
 	intents       map[string]*ports.TimedIntent
 	vtxos         map[string]struct{}
 	vtxosToRemove []string
+	poppedIntents []ports.TimedIntent
```
Comment (altafan) [inline internal/infrastructure/live-store/inmemory/intents.go]:
```suggestion
	selectedIntents []ports.TimedIntent
```

File: internal/core/application/service.go [hunk 4]
```diff
@@ -2796,7 +2793,21 @@ func (s *service) propagateEvents(round *domain.Round) {
...
+				topics = append(topics, input.Outpoint.String())
+			}
+
+			for _, boardingInput := range intent.BoardingInputs {
+				topics = append(topics, boardingInput.String())
+			}
+		}
+
+		lastEvent = RoundFailed{ev, topics}
 	}
```
[the remark this answers is not in the document]
Comment (tiero) [reply internal/core/application/service.go:2811]: @louisinger
